### ISSUE TITLE
New concept for waveforms and retracker data/code structure

### ISSUE THREAD

**Issue by shendric** [shendric/pysiral#85]
## Issue with current implementation

Waveform data is stored in the `waveform` data group of the l1p data structure with supporting information, such as waveform shape parameters in the the `classifier` data group. This data is then used in the Level-2 processor for retracking with an implementation based on `l1` and `l2` data objects. With more retrackers and waveform shape parameters being added, the implementation has become increasingly messy, hard to maintain/extent. Some retrackers, such as the TFMRA are implemented in multiple forms 

## What is required?

- Simpler code base
- Better and unified description of waveforms (identification of first maximum, leading edge, trailing edge,  ...)
- Method to counter increased computational demand of physical retrackers and additional waveform shape parameters (e.g. built-in multi-processing capability)
- Separation of retracker algorithm from some specific retracker parametrizations. A particular bad example is the choice of different TFMRA thresholds in:  https://github.com/shendric/pysiral/blob/87723d073a3d080941028874fa1a3fb691befdf2/pysiral/retracker.py#L924 These need to be handled separately. 

## Proposal for Evolution

The task to update the l1p data file structure provides an opportunity to fundamentally change the waveform/retracker handling. The following action may be evaluated

- [ ] Create a `Waveform` class that holds the waveform data and all relevant waveform shape parameters and the range bin classification. Waveform shape parameters should be computed based on this class. 
- [ ] Create a `WaveformCollection` class that used for storing data from a trajectory or respective subsets. The class should also keep information if the waveforms are direct neighbours, e.g. by keeping the waveform index. 
- [ ] Create a retracker package with each retracker as a sub-package. 
- [ ] Each re-implemented retracker class should be able to function with minimum input (#66), but convenient methods for `Waveform` and `WaveformCollection` input should be included
- [ ] Specifically re-implement the TFMRA and move all threshold generation out of the retracker code
- [ ] Add the option to run multiple retrackers per surface type to support R&D activities 

## Linked issues

- #4
- #29  
- #45
- #53 
- #66
