### ISSUE TITLE
Unify auxiliary data classes

### ISSUE THREAD

**Issue by shendric** [shendric/pysiral#9]
### Issue
The current implementation of auxiliary data classes is distributed over the different modules (mss, sic, sitype, snow, ...) and causes a lot of code duplication. E.g. there are super classes for each auxiliary data type that are almost identical, except for the name of the method. 

### ToDo
- [x] Remove the superclasses for each auxiliary data type and replace them with `auxdata.AuxdataBaseClass`
- [x] Implement one getter function that directs to the subclass 
(e.g. `auxdata = AuxDataHandler(auxdata_type, auxdata_pyclass`)
- [x] Unify a common method name to get the data along the track
    - `auxdata.get_track_from_l2(l2)`: for use of the Level-2 processor 
    - `auxdata_get_track(date, lons, lats)`: for general use
- [x] Implement a way to deal with a variable number of resulting variables, e.g.
   - `auxdata.registered_variables`: property that contains the names of the extracted variables 
   - `auxdata.get_variables()`: Return a list of variables
   - `auxdata.get_variable(name)`: Return a list of variables 
   - `auxdata.update_l2(l2)`:  adds the variables to the l2 data object
- [x] While doing this, come up with a better way to handle messages from auxiliary data handler
- [ ] Allow the Datahandler to raise an Exception, if data does not exist (good exercise to learn declarators)
- [ ] Allow a verbose & quit mode
- [x] Change the Level-2 processor settings format accordingly (see below)

The unification of the auxiliary data handler allows to change the number of data handlers in the Level-2 processor. It is intended to change the Level-2 processor settings in the following way: 

#### Current auxdata definition in the l2 proc settings files
```
auxdata:
    
    mss:
        name: dtu15
        options: null
    sic:
        name: osisaf
        options:
           ...
    sitype:
        name: osisaf
        options: null
    snow: 
        name: warren99
        options: 
            ....
```

#### New auxdata definition in the l2 proc settings files (TBD) 
```
auxdata:
    
    - type: mss
      name: dtu15
      options: null

    - type: sic
      name: osisaf
      options:
           ...

    - type: sitype
      name: osisaf
      options: null

    - type: snow
      name: warren99
      options: 
           ....
```

The change from a dictionary to a list allows to loop over all auxiliary data handlers instead of calling them specifically. The auxiliary data handler would then be executed corresponding to their order in the Level-2 processor settings file.

**Comment by shendric** [comment]
A unified approach to auxiliary data handlers has been merged into develop in 104bc60.  A few low priority items were not tackled (verbose & quiet mode), but this issue can be closed for now. 

Please note that the modification requires changes in the l2 proc definition files. Not all are implemented
